spacy_stop_words = [
    'make', 'at', 'move', 'than', 'except', 'full', 'of', 'even', 'myself', 'hundred', 'it',
    'something', 'here', 'well', 'go', 'any', 'thereupon', 'throughout', 'give', 'using', 'less', 'once', 'although',
    'keep', 'fifty', 'twenty', 'nothing', 'through', 'alone', 'be', 'whenever', 'latterly', 'is', 'take', 'least',
    'behind', 'serious', 'between', 'we', 'all', 'eleven', '’ll', 'together', 'those', 'more', 'formerly', 'hers',
    'and', 'latter', '‘re', 'get', 'your', '‘ve', 'yours', '‘m', 'many', 'put', 'she', '’re', 'really',
    'yours', 'elves', 'our', 'several', "'re", 'meanwhile', '’ve', 'either', 'each', 'seemed', 'does', 'say',
    'another', 'whence', 'to', 'yourself', 'nor', 'almost', 'during', 'onto', 'up', 'anyway', 'whole', 'every',
    'whoever', 'this', 'in', 'an', 'some', 'amount', 'hereafter', 'no', 'that', 'was', 'often', 'me', 'whereafter',
    'wherever', 'bottom', 'three', '‘s', 'used', 'yet', 'hereupon', 're', 'mostly', 'his', 'however', 'next', 'beyond',
    'never', 'empty', "'ve", 'after', 'name', 'so', 'others', 'the', 'becomes', 'neither', 'herself',
    'own', 'by', '‘d', 'since', 'before', 'i', 'are', 'as', 'into', 'further', 'somehow', 'why', 'unless', 'back',
    'mine', 'too', 'via', 'ever', 'when', 'few', 'also', 'anything', 'top', 'can', 'thus', 'done', 'for', 'see',
    'without', 'please', 'them', "'ll", 'whereby', 'along', 'beforehand', 'upon', 'seeming', 'with', 'whether',
    'eight', 'toward', 'whereupon', 'other', 'though', 'everyone', 'seems', 'hereby', 'therein', 'twelve',
    'about', 'thereby', 'afterwards', 'their', 'ourselves', 'could', 'him', 'one', 'above', 'fifteen', 'six',
    'below', 'has', 'nevertheless', 'becoming', 'itself', 'because', 'thru', 'already', 'among', 'doing', 'what',
    'everything', 'herein', 'themselves', 'thence', 'its', 'ca', 'various', "'m", 'whatever', 'anyhow', 'third',
    'forty', 'or', 'himself', 'am', 'nobody', 'everywhere', 'hence', 'last', 'against', 'same', 'sometime',
    'wherein', 'us', 'her', 'towards', 'how', 'whereas', 'have', 'two', 'may', 'former', 'across', 'now',
    'then', 'enough', 'they', 'my', 'a', 'which', 'should', 'indeed', 'therefore', "'s", 'n’t', 'ours', 'such', 'ten',
    'front', 'quite', 'these', 'over', 'been', 'sometimes', 'made', 'there', 'while', 'n‘t', '’d',
    'down', 'nine', 'very', '’m', 'were', 'call', '’s', 'most', 'must', 'elsewhere',
    'under', '‘ll', 'noone', 'you', "n't", 'only', 'show', 'but', 'both', 'otherwise', 'per', 'perhaps',
    'become', 'side', 'seem', 'on', 'whom', 'namely', 'had', 'became', 'part', 'besides', 'amongst', 'cannot', 'else',
    'might', 'regarding', 'four', 'nowhere', 'out', 'anyone', 'rather', 'would', 'from', 'will', 'if', 'again',
    'around', 'until', 'just', 'five', 'within', 'much', 'always', 'still', 'do', 'thereafter', 'whither', 'someone',
    'off', 'being', 'where', 'whose', 'sixty', 'not', 'who', 'none', "'d""", 'beside', 'anywhere', 'somewhere',
    'moreover', 'did', 'due', 'he', 'first']
