# Generated by Django 3.2.9 on 2021-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoredAndJoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('actividad', models.TextField(verbose_name='actividad')),
                ('key', models.PositiveIntegerField()),
                ('chiste', models.TextField(verbose_name='chiste')),
            ],
        ),
    ]
